// ── Structured IDP / LTDP Library ──
// Organized by age group × development pillar
// Each entry is a pre-built development pathway

export const AGE_GROUPS = {
  foundation: {
    label: "Foundation",
    icon: "🌱",
    range: "U10–U12",
    ageRange: [10, 12],
    color: "#22c55e",
    description: "Fun, fundamentals, and love for the game. Small-sided play with lots of touches.",
    focus: "Build a broad movement and ball-mastery foundation. Every session should be fun first.",
    trainingDays: 3,
    sessionMinutes: 60,
    ltdpPhase: "FUNdamentals & Learning to Train",
  },
  development: {
    label: "Development",
    icon: "📈",
    range: "U13–U15",
    ageRange: [13, 15],
    color: "#f97316",
    description: "Skill refinement, tactical introduction, and physical growth awareness.",
    focus: "Golden age of skill acquisition. Introduce tactical concepts through small-sided games.",
    trainingDays: 4,
    sessionMinutes: 75,
    ltdpPhase: "Training to Train & Training to Compete",
  },
  performance: {
    label: "Performance",
    icon: "🔥",
    range: "U16–U18",
    ageRange: [16, 18],
    color: "#ef4444",
    description: "Advanced tactics, physical conditioning, and mental preparation for competition.",
    focus: "Position-specific specialization. High-intensity training with tactical periodization.",
    trainingDays: 5,
    sessionMinutes: 90,
    ltdpPhase: "Training to Compete & Training to Win",
  },
  elite: {
    label: "Elite",
    icon: "💎",
    range: "19+",
    ageRange: [19, 99],
    color: "#8b5cf6",
    description: "High performance, specialization, and professional preparation.",
    focus: "Maximize performance in all pillars. Individualize programming for peak output.",
    trainingDays: 6,
    sessionMinutes: 100,
    ltdpPhase: "Training to Win & Active for Life",
  },
};

export function getAgeGroup(age) {
  for (const [key, group] of Object.entries(AGE_GROUPS)) {
    if (age >= group.ageRange[0] && age <= group.ageRange[1]) return { key, ...group };
  }
  return { key: "elite", ...AGE_GROUPS.elite };
}

// ── Pillar definitions ──
export const PILLARS = {
  technical:  { label: "Technical",  icon: "⚽",  color: "#22c55e", desc: "Ball mastery, first touch, passing, shooting, dribbling" },
  physical:   { label: "Physical",   icon: "💪", color: "#ef4444", desc: "Speed, agility, strength, endurance, coordination" },
  tactical:   { label: "Tactical",   icon: "📋", color: "#f97316", desc: "Game understanding, positioning, decision-making, formations" },
  mental:     { label: "Mental",     icon: "🧠", color: "#06b6d4", desc: "Confidence, focus, resilience, visualization, mindset" },
  nutrition:  { label: "Nutrition",  icon: "🥗", color: "#eab308", desc: "Fueling, hydration, meal timing, recovery nutrition" },
  recovery:   { label: "Recovery",   icon: "🛌", color: "#8b5cf6", desc: "Sleep, active recovery, injury prevention, mobility" },
};

// ── Structured IDP per age group × pillar ──
// Each entry: { vision, phases: [{ name, weeks, focus, goals, milestones, key_skills, drills }] }

export const IDP_LIBRARY = {
  foundation: {
    technical: {
      vision: "Develop a love for the ball. Master basic ball control on the ground with both feet. Build the habit of daily touches.",
      phases: [
        {
          name: "Ball Familiarity",
          weeks: 12,
          focus: "Comfort with the ball at feet. Dribbling, stopping, turning.",
          goals: ["100 consecutive juggles", "Dribble through 8 cones without losing control", "10 accurate passes to a partner from 5 yards"],
          milestones: [{ name: "50 juggles", metric: "50 consecutive touches" }, { name: "Cone weave under 20s", metric: "Complete 8-cone weave" }],
          key_skills: ["Dribbling", "Ball control", "Basic turns", "Short passing"],
          drills: ["Cone Dribbling", "Juggling Challenge", "Wall Passes", "Red Light Green Light", "Sharks and Minnows"],
        },
        {
          name: "Passing & Receiving",
          weeks: 12,
          focus: "Accurate short passing and receiving the ball cleanly.",
          goals: ["15 consecutive passes with partner", "Receive and pass within 2 touches", "Pass to a moving target"],
          milestones: [{ name: "Passing accuracy 80%", metric: "8/10 passes on target at 5yd" }, { name: "First touch control", metric: "Control 8/10 serves" }],
          key_skills: ["Passing", "Receiving", "Two-touch play", "Communication"],
          drills: ["Passing Pairs", "Triangle Passing", "1-Touch Circle", "Receive & Turn", "Target Passing"],
        },
        {
          name: "Small-Sided Play",
          weeks: 12,
          focus: "Apply skills in 2v2 and 3v3 games. Learn to share space and make simple decisions.",
          goals: ["Score in small-sided games", "Make 3 successful passes in a row during play", "Learn to spread out"],
          milestones: [{ name: "Game confidence", metric: "Comfortable in 3v3" }, { name: "Decision making", metric: "Can explain 3 basic choices" }],
          key_skills: ["Spatial awareness", "Teamwork", "Decision-making", "Fun"],
          drills: ["3v3 Small Goals", "2v2 Keepaway", "Numbers Game", "4-Goal Game", "Dribble Relay"],
        },
        {
          name: "All-Around Fun",
          weeks: 16,
          focus: "Consolidate skills through varied, fun activities. Introduce weak foot and shooting basics.",
          goals: ["Score from 8 yards with both feet", "10 juggles with weak foot", "Complete a full 4v4 game understanding the rules"],
          milestones: [{ name: "Both-foot comfort", metric: "Can dribble 10yd with weak foot" }, { name: "Game understanding", metric: "Knows positions in 4v4" }],
          key_skills: ["Shooting", "Weak foot", "Game rules", "Fun"],
          drills: ["Shooting Gallery", "Weak Foot Challenge", "4v4 Tournament", "Skill Circuit", "Fun Games"],
        },
      ],
    },
    physical: {
      vision: "Develop fundamental movement skills (agility, balance, coordination, speed). Make physical activity fun and varied.",
      phases: [
        {
          name: "Movement ABCs",
          weeks: 12,
          focus: "Agility, balance, and coordination through playful activities.",
          goals: ["Complete a basic agility ladder sequence", "Balance on each leg for 20s", "Run, jump, and land safely"],
          milestones: [{ name: "Agility ladder mastery", metric: "3 patterns at speed" }, { name: "Balance test", metric: "20s single-leg balance" }],
          key_skills: ["Agility", "Balance", "Coordination", "Body awareness"],
          drills: ["Agility Ladder", "Animal Walks", "Balance Games", "Tag Variations", "Obstacle Course"],
        },
        {
          name: "Speed & Quickness",
          weeks: 12,
          focus: "Linear speed, change of direction, and reaction time.",
          goals: ["Sprint 15m in under 4s", "Complete 5-10-5 shuttle in under 8s", "React to a visual cue within 1s"],
          milestones: [{ name: "Speed baseline", metric: "15m sprint time recorded" }, { name: "Agility test", metric: "5-10-5 shuttle recorded" }],
          key_skills: ["Sprint mechanics", "Change of direction", "Reaction", "Acceleration"],
          drills: ["Sprint Intervals", "Reaction Starts", "Shuttle Runs", "Mirror Drill", "Cone Chase"],
        },
        {
          name: "Strength Foundations",
          weeks: 12,
          focus: "Bodyweight strength — push, pull, squat, lunge, core.",
          goals: ["15 proper push-ups", "20 bodyweight squats", "30s plank hold"],
          milestones: [{ name: "Push-up test", metric: "15 consecutive" }, { name: "Core endurance", metric: "45s plank" }],
          key_skills: ["Push/pull strength", "Core stability", "Squat pattern", "Lunge pattern"],
          drills: ["Core Circuit", "Squat & Lunge Challenge", "Push-Up Ladder", "Animal Moves", "Partner Resistance"],
        },
        {
          name: "Athletic Play",
          weeks: 16,
          focus: "Combine speed, agility, and strength in game-like movement patterns.",
          goals: ["Complete a full athletic circuit", "Show improved sprint times", "Move efficiently in all directions"],
          milestones: [{ name: "Circuit completion", metric: "Full athletic circuit under 5 min" }, { name: "Movement efficiency", metric: "Smooth multi-directional movement" }],
          key_skills: ["Multi-directional speed", "Movement economy", "Stamina", "Enjoyment"],
          drills: ["Athletic Circuit", "Game-Like Movement", "Relay Races", "Capture the Flag", "Parkour Basics"],
        },
      ],
    },
    tactical: {
      vision: "Introduce basic game concepts through small-sided play. Learn positions, spacing, and simple rules.",
      phases: [
        {
          name: "Game Basics",
          weeks: 12,
          focus: "Understanding positions, boundaries, and basic rules.",
          goals: ["Name all positions in 4v4", "Understand offside basics", "Know how to restart play"],
          milestones: [{ name: "Position knowledge", metric: "Can name 4 positions" }, { name: "Rule understanding", metric: "Explains 5 basic rules" }],
          key_skills: ["Position names", "Boundaries", "Restarts", "Basic rules"],
          drills: ["Position Awareness", "Formation Basics", "Rules Quiz", "Small-Sided Scrimmage"],
        },
        {
          name: "Spacing & Shape",
          weeks: 12,
          focus: "Spread out when attacking, get compact when defending.",
          goals: ["Maintain width in attack", "Stay connected to teammates", "Recognize when to press"],
          milestones: [{ name: "Spacing test", metric: "Can spread to all zones in 4v4" }, { name: "Defensive shape", metric: "Stays compact defensively" }],
          key_skills: ["Width", "Compactness", "Connection", "Pressing trigger"],
          drills: ["Spread Out Game", "Defensive Shape", "Channel Game", "3-Zone Scrimmage"],
        },
        {
          name: "Simple Decisions",
          weeks: 12,
          focus: "Dribble or pass? Shoot or keep the ball? Basic decision-making under no pressure.",
          goals: ["Make the right pass 60% of the time", "Know when to dribble vs pass", "Take a shot when open"],
          milestones: [{ name: "Decision speed", metric: "Decides within 2s of receiving" }, { name: "Pass vs dribble", metric: "Makes correct choice 6/10 times" }],
          key_skills: ["Decision-making", "Risk assessment", "Scanning", "Option awareness"],
          drills: ["Dribble or Pass Drill", "Shoot or Keep", "Numbers-Up Attack", "Coach Questions"],
        },
        {
          name: "Game Understanding",
          weeks: 16,
          focus: "Apply tactical concepts in varied game formats with guided discovery.",
          goals: ["Play multiple positions", "Adapt to different game formats", "Explain what went well/didn't in a game"],
          milestones: [{ name: "Multi-position", metric: "Comfortable in 2+ positions" }, { name: "Self-reflection", metric: "Can analyze own game" }],
          key_skills: ["Versatility", "Adaptability", "Self-analysis", "Communication"],
          drills: ["Position Rotation Games", "Video Review", "Captain for a Day", "Tactical Puzzle"],
        },
      ],
    },
    mental: {
      vision: "Build confidence through competence. Make mistakes okay. Develop a growth mindset and love for practice.",
      phases: [
        {
          name: "Confidence Building",
          weeks: 12,
          focus: "Celebrate effort over outcome. Every player feels successful.",
          goals: ["Try new skills without fear", "Celebrate teammates' success", "Say one positive thing about training"],
          milestones: [{ name: "Effort mindset", metric: "Tries new things consistently" }, { name: "Team spirit", metric: "Cheers for teammates" }],
          key_skills: ["Confidence", "Effort celebration", "Positivity", "Bravery"],
          drills: ["Compliment Circle", "Skill Showcase", "Effort Awards", "Brave Try Challenge"],
        },
        {
          name: "Growth Mindset",
          weeks: 12,
          focus: "Understand that skills grow with practice. 'I can't do it YET.'",
          goals: ["Use 'yet' language naturally", "Track personal improvement", "Set one small goal per week"],
          milestones: [{ name: "Growth language", metric: "Uses growth-mindset phrases" }, { name: "Goal setting", metric: "Sets weekly training goal" }],
          key_skills: ["Growth mindset", "Goal setting", "Self-tracking", "Persistence"],
          drills: ["Goal Setting Journal", "Before & After", "Progress Chart", "Role Model Stories"],
        },
        {
          name: "Focus & Listening",
          weeks: 12,
          focus: "Develop concentration skills. Listen to coaches and teammates.",
          goals: ["Focus for a full drill without distraction", "Follow 3-step instructions", "Wait for turn patiently"],
          milestones: [{ name: "Focus duration", metric: "15 min sustained attention" }, { name: "Instruction recall", metric: "Remembers 3-step sequences" }],
          key_skills: ["Focus", "Listening", "Patience", "Self-control"],
          drills: ["Coach Says", "Memory Game", "Focus Circle", "Quiet Ball"],
        },
        {
          name: "Resilience",
          weeks: 16,
          focus: "Bounce back from mistakes. Learn from losses. Keep trying after failure.",
          goals: ["Recover within 30s after a mistake", "Say 'I'll try again' after failure", "Stay positive after a loss"],
          milestones: [{ name: "Recovery speed", metric: "Bounces back quickly" }, { name: "Post-loss positivity", metric: "Finds learning after losses" }],
          key_skills: ["Resilience", "Emotional control", "Learning from failure", "Optimism"],
          drills: ["Mistake Reset", "Win/Loss Reflection", "Resilience Stories", "Bounce-Back Game"],
        },
      ],
    },
    nutrition: {
      vision: "Learn the basics of healthy eating. Understand that food is fuel for play. Build hydration habits.",
      phases: [
        {
          name: "Food as Fuel",
          weeks: 12,
          focus: "Understand that food gives energy to play. Identify healthy vs treat foods.",
          goals: ["Name 5 healthy foods", "Name 3 foods to eat before training", "Understand why water matters"],
          milestones: [{ name: "Food knowledge", metric: "Can categorize foods" }, { name: "Hydration awareness", metric: "Knows to bring water" }],
          key_skills: ["Food awareness", "Hydration basics", "Healthy choices", "Fuel timing"],
          drills: ["Food Group Game", "Fuel Plate Drawing", "Water Tracker Star Chart"],
        },
        {
          name: "Pre-Game Eating",
          weeks: 12,
          focus: "What to eat before practice and games. Timing of meals.",
          goals: ["Eat a proper pre-training snack", "Wait 1 hour after eating before playing", "Bring water to every session"],
          milestones: [{ name: "Pre-training routine", metric: "Consistent pre-training snack" }, { name: "Water habit", metric: "Brings water 5/5 sessions" }],
          key_skills: ["Pre-training nutrition", "Meal timing", "Hydration habit"],
          drills: ["Pre-Training Checklist", "Timing Chart", "Water Bottle Decorating"],
        },
        {
          name: "Balanced Plate",
          weeks: 12,
          focus: "Learn the plate method: half fruits/veg, quarter protein, quarter carbs.",
          goals: ["Build a balanced plate", "Try one new healthy food per week", "Understand protein helps muscles"],
          milestones: [{ name: "Plate building", metric: "Can build balanced plate" }, { name: "Food adventure", metric: "Tried 8 new foods" }],
          key_skills: ["Balanced eating", "Food variety", "Protein awareness"],
          drills: ["Build Your Plate", "New Food Challenge", "Protein Power Game"],
        },
        {
          name: "Healthy Habits",
          weeks: 16,
          focus: "Consolidate nutrition knowledge into daily habits. Make good choices independently.",
          goals: ["Choose water over soda", "Eat breakfast every day", "Help with meal preparation"],
          milestones: [{ name: "Independent choices", metric: "Makes healthy choices without prompting" }, { name: "Breakfast streak", metric: "7-day breakfast streak" }],
          key_skills: ["Independent choices", "Habit formation", "Meal involvement"],
          drills: ["Habit Tracker", "Cooking Helper", "Snack Swap Challenge"],
        },
      ],
    },
    recovery: {
      vision: "Learn that rest makes you stronger. Good sleep = better play. Listen to your body.",
      phases: [
        {
          name: "Sleep is Training",
          weeks: 12,
          focus: "Understand why sleep matters for growth and performance.",
          goals: ["Sleep 9-10 hours per night", "Have a bedtime routine", "No screens 30 min before bed"],
          milestones: [{ name: "Sleep duration", metric: "9+ hours consistently" }, { name: "Bedtime routine", metric: "Follows routine 5/7 nights" }],
          key_skills: ["Sleep hygiene", "Bedtime routine", "Screen limits"],
          drills: ["Sleep Tracker", "Bedtime Routine Builder", "Screen-Free Challenge"],
        },
        {
          name: "Active Recovery",
          weeks: 12,
          focus: "Light movement on rest days. Stretching basics.",
          goals: ["Do light activity on off days", "Learn 5 basic stretches", "Understand the difference between soreness and pain"],
          milestones: [{ name: "Active recovery habit", metric: "Moves on 2+ off days/week" }, { name: "Stretch knowledge", metric: "Can lead 5 stretches" }],
          key_skills: ["Active recovery", "Basic stretching", "Body listening"],
          drills: ["Stretch Routine", "Light Play Day", "Body Check-In", "Soreness Scale"],
        },
        {
          name: "Body Awareness",
          weeks: 12,
          focus: "Recognize fatigue, soreness, and when to rest.",
          goals: ["Use a 1-10 fatigue scale", "Tell coach about pain", "Take rest when needed"],
          milestones: [{ name: "Fatigue awareness", metric: "Accurate self-rating" }, { name: "Communication", metric: "Reports pain/discomfort" }],
          key_skills: ["Fatigue recognition", "Pain reporting", "Rest advocacy"],
          drills: ["Fatigue Scale Check", "Pain vs Soreness Game", "Rest Day Bingo"],
        },
        {
          name: "Recovery Routine",
          weeks: 16,
          focus: "Build a complete recovery routine: sleep, nutrition timing, light movement.",
          goals: ["Follow full recovery routine", "Sleep well consistently", "Feel fresh for training"],
          milestones: [{ name: "Recovery routine", metric: "Complete routine 4/7 days" }, { name: "Freshness check", metric: "Self-reports feeling fresh" }],
          key_skills: ["Complete recovery", "Consistency", "Self-care"],
          drills: ["Recovery Checklist", "Freshness Journal", "Weekend Recovery"],
        },
      ],
    },
  },

  development: {
    technical: {
      vision: "Golden age of skill acquisition. Master ball control at speed, develop both feet, and learn advanced techniques. Every touch counts.",
      phases: [
        {
          name: "Ball Mastery Acceleration",
          weeks: 12,
          focus: "Advanced dribbling at speed, 1v1 moves, and close control under pressure.",
          goals: ["Complete 5 skill moves at game speed", "200+ consecutive juggles alternating feet", "Beat a defender 1v1 in tight space"],
          milestones: [{ name: "Skill moves test", metric: "5 moves at full speed" }, { name: "Juggling benchmark", metric: "200+ alternating feet" }],
          key_skills: ["1v1 attacking", "Close control", "Skill moves", "Speed dribbling"],
          drills: ["Skill Moves Combo", "1v1 to Goal", "Speed Dribble Course", "Weak Foot Training", "First Touch Drill"],
        },
        {
          name: "Passing Range & Accuracy",
          weeks: 12,
          focus: "Develop long and short passing accuracy. Weighted passes and through balls.",
          goals: ["Complete 20-yard accurate pass 8/10", "Thread through balls between defenders", "One-touch passing under pressure"],
          milestones: [{ name: "Passing accuracy", metric: "80% at 20 yards" }, { name: "Through-ball test", metric: "5/10 successful through balls" }],
          key_skills: ["Long passing", "Through balls", "One-touch", "Pass weighting"],
          drills: ["Long Pass Challenge", "Through Ball Gates", "1-Touch Rondo", "Switching Play", "Passing Ladder"],
        },
        {
          name: "Finishing & Shooting",
          weeks: 12,
          focus: "Shooting technique with both feet. Finishing from different angles and situations.",
          goals: ["Score 7/10 from inside the box", "Shoot with power and accuracy from 18 yards", "Finish with weak foot 5/10"],
          milestones: [{ name: "Finishing test", metric: "Score 7/10 in-box" }, { name: "Distance shooting", metric: "5/10 from 18 yards on target" }],
          key_skills: ["Finishing", "Shooting power", "Weak foot shooting", "Volleys"],
          drills: ["Advanced Finishing", "Shooting Circuit", "Weak Foot Strikes", "Volley Practice", "1v1 vs GK"],
        },
        {
          name: "Position-Specific Technique",
          weeks: 16,
          focus: "Refine techniques specific to playing position. Combine technical skills in game scenarios.",
          goals: ["Master 3 position-specific techniques", "Execute combinations in small-sided games", "Show technical consistency in matches"],
          milestones: [{ name: "Position mastery", metric: "3 position skills at game speed" }, { name: "Match consistency", metric: "Technical accuracy in games" }],
          key_skills: ["Position technique", "Combination play", "Match application", "Consistency"],
          drills: ["Combination Play", "Position Circuit", "Match Simulation", "Under Pressure", "Creative Play"],
        },
      ],
    },
    physical: {
      vision: "Develop speed, strength, and conditioning during the growth spurt window. Build an athletic foundation for the performance years.",
      phases: [
        {
          name: "Speed Development",
          weeks: 12,
          focus: "Linear speed mechanics, acceleration, and top-end speed.",
          goals: ["Improve 20m sprint by 0.2s", "Master proper sprint mechanics", "Maintain speed through direction change"],
          milestones: [{ name: "20m sprint", metric: "Timed benchmark" }, { name: "Sprint form", metric: "Coach assessment of mechanics" }],
          key_skills: ["Acceleration", "Top speed", "Sprint mechanics", "Deceleration"],
          drills: ["Speed & Agility", "Sprint Intervals", "Resisted Sprints", "Flying 20's", "Technique Drills"],
        },
        {
          name: "Strength Building",
          weeks: 12,
          focus: "Introduction to resistance training. Bodyweight mastery and light external loads.",
          goals: ["20 push-ups with perfect form", "10 pull-ups", "Bodyweight squat with proper depth"],
          milestones: [{ name: "Push-up test", metric: "20 perfect form" }, { name: "Pull-up test", metric: "10 consecutive" }],
          key_skills: ["Push/pull strength", "Squat mechanics", "Core strength", "Body control"],
          drills: ["Strength Circuit", "Push-Up/Pull-Up Ladder", "Core Circuit", "Squat Progression", "Band Work"],
        },
        {
          name: "Agility & Change of Direction",
          weeks: 12,
          focus: "Multi-directional speed. Reactive agility and cutting mechanics.",
          goals: ["Improve 5-10-5 shuttle by 0.3s", "React and change direction within 1s", "Show efficient cutting technique"],
          milestones: [{ name: "5-10-5 test", metric: "Timed benchmark" }, { name: "Reactive test", metric: "Coach-scored agility" }],
          key_skills: ["Cutting", "Reactive agility", "Lateral speed", "Deceleration"],
          drills: ["HIIT Pitch Workout", "T-Drill", "Pro-Agility", "Reactive Mirror", "Cone Cutting"],
        },
        {
          name: "Conditioning & Endurance",
          weeks: 16,
          focus: "Aerobic base for soccer. Game-specific interval conditioning.",
          goals: ["Complete a 12-min Cooper test at age standard", "Maintain high intensity through a full match", "Recover quickly between efforts"],
          milestones: [{ name: "Cooper test", metric: "Age-norm benchmark" }, { name: "Match endurance", metric: "Full match at high tempo" }],
          key_skills: ["Aerobic capacity", "Repeat-sprint ability", "Recovery between efforts", "Pacing"],
          drills: ["Endurance Run", "SAQ Complex", "Interval Sprints", "Match Fitness Protocol", "Fartlek"],
        },
      ],
    },
    tactical: {
      vision: "Develop game intelligence. Understand team shape, roles, and decision-making. Read the game and anticipate.",
      phases: [
        {
          name: "Position Understanding",
          weeks: 12,
          focus: "Deep dive into player's primary position. Responsibilities in all phases.",
          goals: ["Explain role in attack, defence, and transition", "Anticipate 3 plays per half", "Stay positionally disciplined"],
          milestones: [{ name: "Position knowledge", metric: "Explains all phase roles" }, { name: "Anticipation", metric: "3+ anticipatory actions per half" }],
          key_skills: ["Positional discipline", "Phase understanding", "Anticipation", "Reading cues"],
          drills: ["Video Analysis", "Position-Specific Shadow Play", "Phase Training", "Game Reading"],
        },
        {
          name: "Team Shape & Systems",
          weeks: 12,
          focus: "Understand formations (4-3-3, 4-4-2, 4-2-3-1). How the team moves as a unit.",
          goals: ["Maintain shape in 3 formations", "Identify shape breakdowns", "Communicate shape adjustments"],
          milestones: [{ name: "Formation fluency", metric: "Comfortable in 3 systems" }, { name: "Shape communication", metric: "Calls adjustments during play" }],
          key_skills: ["Formations", "Unit movement", "Compactness", "Communication"],
          drills: ["Defensive Shape", "Formation Walk-Through", "Shape vs Ball Movement", "Unit Shift Drill"],
        },
        {
          name: "Decision-Making Under Pressure",
          weeks: 12,
          focus: "Make the right decision quickly. Scanning before receiving. Options hierarchy.",
          goals: ["Scan 3+ times before receiving", "Make correct decision 70% of time", "Execute under pressure"],
          milestones: [{ name: "Scanning test", metric: "3+ scans before receiving" }, { name: "Decision accuracy", metric: "70% correct decisions" }],
          key_skills: ["Scanning", "Decision speed", "Pressure composure", "Option selection"],
          drills: ["Pressing Trigger Drill", "Transition Sprint", "Counter-Attack Drill", "Overload Games"],
        },
        {
          name: "Match Strategy",
          weeks: 16,
          focus: "Game management. Adapting tactics during matches. Set pieces and special situations.",
          goals: ["Read game state and adjust", "Execute set-piece routines", "Manage different scoreline situations"],
          milestones: [{ name: "Game management", metric: "Adjusts play to game state" }, { name: "Set piece execution", metric: "Executes 3 routines accurately" }],
          key_skills: ["Game management", "Set pieces", "Adaptability", "Leadership"],
          drills: ["Corner Routines", "Free Kick Patterns", "Protect the Lead", "Chasing the Game", "10-Men Scenario"],
        },
      ],
    },
    mental: {
      vision: "Build mental toughness. Develop pre-game routines, focus techniques, and emotional control. Handle pressure and adversity.",
      phases: [
        {
          name: "Pre-Game Preparation",
          weeks: 12,
          focus: "Develop a consistent pre-game routine. Visualization and goal setting.",
          goals: ["Create and follow a pre-game routine", "Use visualization before games", "Set 3 process goals per game"],
          milestones: [{ name: "Routine consistency", metric: "Follows routine every game" }, { name: "Visualization use", metric: "Uses visualization pre-game" }],
          key_skills: ["Pre-game routine", "Visualization", "Process goals", "Preparation"],
          drills: ["Pre-Game Routine Builder", "Visualization Practice", "Goal-Setting Journal", "Game Preparation Checklist"],
        },
        {
          name: "Focus & Concentration",
          weeks: 12,
          focus: "Maintain focus through distractions. Reset after mistakes. Present-moment awareness.",
          goals: ["Refocus within 10s after a mistake", "Stay focused through full training session", "Block out crowd/noise distraction"],
          milestones: [{ name: "Reset speed", metric: "Refocuses in under 10s" }, { name: "Focus endurance", metric: "Sustained focus 60 min" }],
          key_skills: ["Present-moment focus", "Mistake recovery", "Distraction blocking", "Attention control"],
          drills: ["Focus Reset Routine", "Concentration Grid", "Distraction Training", "Breath Focus"],
        },
        {
          name: "Confidence & Self-Talk",
          weeks: 12,
          focus: "Build genuine confidence through preparation. Develop positive self-talk.",
          goals: ["Use positive self-talk in games", "List 5 strengths confidently", "Overcome negative thoughts within 30s"],
          milestones: [{ name: "Self-talk quality", metric: "Uses positive language" }, { name: "Confidence scale", metric: "Self-rates confidence 7+/10" }],
          key_skills: ["Self-talk", "Confidence", "Strength awareness", "Thought management"],
          drills: ["Confidence Journal", "Positive Self-Talk Scripts", "Strength Assessment", "Power Pose Routine"],
        },
        {
          name: "Resilience & Adversity",
          weeks: 16,
          focus: "Handle losses, mistakes, and setbacks. Growth through challenge. Mental toughness.",
          goals: ["Recover emotionally after a loss within 24h", "Find learning in every setback", "Maintain effort when losing"],
          milestones: [{ name: "Resilience rating", metric: "Coach-scored resilience 8+/10" }, { name: "Adversity response", metric: "Stays composed in difficult moments" }],
          key_skills: ["Emotional control", "Learning from adversity", "Persistence", "Perspective"],
          drills: ["Adversity Scenarios", "Post-Game Reflection", "Gratitude Practice", "Challenge Mindset Training"],
        },
      ],
    },
    nutrition: {
      vision: "Fuel for growth and performance. Understand macros, meal timing, and sports nutrition. Make independent healthy choices.",
      phases: [
        {
          name: "Performance Nutrition Basics",
          weeks: 12,
          focus: "Macronutrients for athletes. Carbs for energy, protein for repair, fats for health.",
          goals: ["Identify carb, protein, and fat sources", "Build a training-day meal plan", "Understand why athletes need more fuel"],
          milestones: [{ name: "Macro knowledge", metric: "Correctly identifies macros" }, { name: "Meal planning", metric: "Builds training-day meal plan" }],
          key_skills: ["Macro awareness", "Meal planning", "Performance fueling", "Label reading"],
          drills: ["Macro Matching Game", "Training Day Meal Builder", "Label Detective", "Athlete Plate Method"],
        },
        {
          name: "Pre & Post Training Fuel",
          weeks: 12,
          focus: "What to eat before and after training. Timing windows for optimal performance and recovery.",
          goals: ["Eat properly 2-3h before training", "Refuel within 30 min after training", "Plan snacks for tournament days"],
          milestones: [{ name: "Pre-training compliance", metric: "Proper pre-fuel 80% of sessions" }, { name: "Post-training refuel", metric: "Refuels within 30 min" }],
          key_skills: ["Timing", "Pre-training meals", "Recovery nutrition", "Tournament fueling"],
          drills: ["Timing Worksheet", "Snack Preparation", "Tournament Meal Plan", "Recovery Smoothie Builder"],
        },
        {
          name: "Hydration Strategy",
          weeks: 12,
          focus: "Hydrate for performance. Electrolytes. Monitoring hydration status.",
          goals: ["Drink 500ml 2h before training", "Monitor urine color for hydration", "Replace fluids after sessions"],
          milestones: [{ name: "Hydration habit", metric: "Pre-hydrates before sessions" }, { name: "Self-monitoring", metric: "Checks hydration status daily" }],
          key_skills: ["Hydration timing", "Electrolyte balance", "Self-monitoring", "Fluid replacement"],
          drills: ["Hydration Schedule", "Urine Color Chart", "Electrolyte Education", "Hydration Log"],
        },
        {
          name: "Independent Nutrition",
          weeks: 16,
          focus: "Make healthy food choices independently. Plan and prepare meals. Understand supplements.",
          goals: ["Plan a week of training meals", "Prepare basic pre/post snacks", "Make informed choices eating out"],
          milestones: [{ name: "Weekly planning", metric: "Plans full week of meals" }, { name: "Preparation skills", metric: "Prepares 3+ snacks/meals" }],
          key_skills: ["Meal independence", "Food preparation", "Informed choices", "Supplement awareness"],
          drills: ["Weekly Meal Planning", "Cooking Basics", "Restaurant Guide", "Supplement Education"],
        },
      ],
    },
    recovery: {
      vision: "Prioritize recovery as part of training. Sleep, nutrition timing, active recovery, and injury prevention. Recovery = growth.",
      phases: [
        {
          name: "Sleep Optimization",
          weeks: 12,
          focus: "Quality sleep as the #1 recovery tool. Sleep hygiene and consistency.",
          goals: ["Sleep 8-10 hours consistently", "Maintain consistent sleep/wake times", "Create an optimal sleep environment"],
          milestones: [{ name: "Sleep consistency", metric: "Same bed/wake time 5+/week" }, { name: "Sleep duration", metric: "8+ hours consistently" }],
          key_skills: ["Sleep hygiene", "Routine", "Environment", "Consistency"],
          drills: ["Sleep Journal", "Environment Checklist", "Wind-Down Routine", "Screen Limits"],
        },
        {
          name: "Active Recovery & Mobility",
          weeks: 12,
          focus: "Movement on rest days. Foam rolling, dynamic stretching, and mobility work.",
          goals: ["Complete active recovery 2x/week", "Learn full foam-rolling routine", "Improve mobility in key areas"],
          milestones: [{ name: "Recovery habit", metric: "Active recovery 2x/week" }, { name: "Mobility screen", metric: "Improved mobility scores" }],
          key_skills: ["Active recovery", "Foam rolling", "Mobility", "Stretching"],
          drills: ["Foam Rolling Routine", "Dynamic Stretch Flow", "Mobility Circuit", "Recovery Day Plan"],
        },
        {
          name: "Injury Prevention",
          weeks: 12,
          focus: "Pre-habilitation exercises. Listening to body signals. Managing load.",
          goals: ["Complete pre-hab routine 3x/week", "Identify early warning signs", "Communicate pain/discomfort promptly"],
          milestones: [{ name: "Pre-hab compliance", metric: "Completes routine 3x/week" }, { name: "Injury awareness", metric: "Reports issues early" }],
          key_skills: ["Pre-hab", "Body awareness", "Load management", "Communication"],
          drills: ["Injury Prevention Circuit", "Body Check-In", "Load Tracking", "Warning Signs Education"],
        },
        {
          name: "Recovery Lifestyle",
          weeks: 16,
          focus: "Integrate recovery into daily life. Balance training, school, social life, and rest.",
          goals: ["Balance all life demands", "Feel consistently fresh for training", "Avoid overtraining signs"],
          milestones: [{ name: "Life balance", metric: "Self-rated balance 7+/10" }, { name: "Freshness", metric: "Fresh for 80% of sessions" }],
          key_skills: ["Life balance", "Stress management", "Overtraining awareness", "Holistic recovery"],
          drills: ["Weekly Balance Check", "Stress Management", "Recovery Lifestyle Plan", "Overtraining Quiz"],
        },
      ],
    },
  },

  performance: {
    technical: {
      vision: "Technical excellence under match pressure. Position-specific mastery. Creative expression within tactical structure. Execution at game speed.",
      phases: [
        {
          name: "Advanced Ball Mastery",
          weeks: 12,
          focus: "Elite-level close control, first touch under pressure, and creative dribbling.",
          goals: ["Execute 8 skill moves spontaneously in matches", "Control any service with first touch", "Create 3+ 1v1 opportunities per match"],
          milestones: [{ name: "Creative moves", metric: "8+ spontaneous moves per match" }, { name: "First-touch rating", metric: "Coach-rated 8+/10" }],
          key_skills: ["Creative dribbling", "Pressure control", "1v1 creation", "Improvisation"],
          drills: ["Creative Play", "Under Pressure", "Advanced Finishing", "Position-Specific Mastery", "Match Simulation"],
        },
        {
          name: "Precision Passing",
          weeks: 12,
          focus: "Line-breaking passes, switches of play, and assists. Passing with purpose.",
          goals: ["Complete 5+ line-breaking passes per match", "Switch play accurately 90%", "Create 3+ scoring chances per match"],
          milestones: [{ name: "Line breaks", metric: "5+ per match" }, { name: "Chance creation", metric: "3+ key passes per match" }],
          key_skills: ["Line-breaking", "Switching play", "Assist creation", "Passing vision"],
          drills: ["Line-Breaking Pass Drill", "Switch of Play", "Assist Challenge", "Vision Training", "Weighted Pass Circuit"],
        },
        {
          name: "Clinical Finishing",
          weeks: 12,
          focus: "Finish from anywhere. All techniques, both feet, any situation.",
          goals: ["Convert 40%+ of chances", "Score with head, both feet, volleys", "Finish from all angles and distances"],
          milestones: [{ name: "Conversion rate", metric: "40%+ shot conversion" }, { name: "Finishing variety", metric: "5+ different finish types in training" }],
          key_skills: ["Finishing variety", "Clinical edge", "Positional finishing", "Composure"],
          drills: ["Finishing Variety Circuit", "Position-Specific Finishing", "Pressure Finishing", "Game-Situation Finishing"],
        },
        {
          name: "Match Technical Performance",
          weeks: 16,
          focus: "Execute all techniques at match intensity. Consistency and reliability under fatigue.",
          goals: ["Maintain technical accuracy at minute 80+", "Complete position-specific actions at 85%+ accuracy", "Be technically reliable in all conditions"],
          milestones: [{ name: "Fatigue accuracy", metric: "85%+ accuracy at 80+ min" }, { name: "Season consistency", metric: "Technical rating stable across season" }],
          key_skills: ["Fatigue resilience", "Technical reliability", "All-conditions execution", "Consistency"],
          drills: ["Fatigue Circuit", "Match Simulation", "All-Conditions Training", "Seasonal Consistency Challenge"],
        },
      ],
    },
    physical: {
      vision: "Elite athleticism. Peak speed, power, strength, and conditioning. Physical dominance on the pitch. Injury resilience.",
      phases: [
        {
          name: "Speed & Power",
          weeks: 12,
          focus: "Max velocity sprinting. Explosive power development. Plyometrics.",
          goals: ["Improve 30m sprint time to elite benchmark", "Increase vertical jump by 3+ inches", "Show explosive first-step acceleration"],
          milestones: [{ name: "30m sprint", metric: "Elite benchmark time" }, { name: "Vertical jump", metric: "3+ inch improvement" }],
          key_skills: ["Max velocity", "Explosive power", "Plyometrics", "First-step"],
          drills: ["Power Training", "Explosive Power", "Sprint Mechanics", "Plyo Circuit", "Olympic Lift Progressions"],
        },
        {
          name: "Strength & Physicality",
          weeks: 12,
          focus: "Functional strength for soccer. Upper and lower body. Core strength.",
          goals: ["Squat 1.5x bodyweight", "Bench press bodyweight", "Show physical dominance in duels"],
          milestones: [{ name: "Strength benchmarks", metric: "Meet position-specific strength standards" }, { name: "Duel success", metric: "Win 60%+ of physical duels" }],
          key_skills: ["Functional strength", "Core power", "Duel dominance", "Physical presence"],
          drills: ["Strength Program", "Core Power", "Duel Training", "Physical Conditioning"],
        },
        {
          name: "Match Conditioning",
          weeks: 12,
          focus: "Soccer-specific endurance. High-intensity repeatability. Recovery between efforts.",
          goals: ["Cover 10km+ in matches at high intensity", "Maintain sprint quality in final 15 min", "Recover between high-intensity efforts within 30s"],
          milestones: [{ name: "Match distance", metric: "10km+ with high-intensity mix" }, { name: "Late-game quality", metric: "Sprint quality maintained through 90 min" }],
          key_skills: ["Match endurance", "Repeat-sprint ability", "Recovery speed", "Pacing"],
          drills: ["Match Fitness Protocol", "Repeat-Sprint Training", "Recovery Interval", "GPS/Load Monitoring"],
        },
        {
          name: "Injury Resilience",
          weeks: 16,
          focus: "Pre-habilitation, load management, and physical robustness.",
          goals: ["Complete season without major injury", "Maintain pre-hab routine consistently", "Manage training load effectively"],
          milestones: [{ name: "Injury-free season", metric: "No missed games from preventable injury" }, { name: "Pre-hab consistency", metric: "90%+ compliance" }],
          key_skills: ["Load management", "Pre-hab", "Recovery discipline", "Body awareness"],
          drills: ["Injury Prevention Program", "Load Monitoring", "Pre-hab Routine", "Recovery Session"],
        },
      ],
    },
    tactical: {
      vision: "Master tactician. Read the game at the highest level. Adapt to any system. Lead tactically on the pitch.",
      phases: [
        {
          name: "Advanced Game Reading",
          weeks: 12,
          focus: "Anticipate 2-3 plays ahead. Recognize patterns. Exploit opposition weaknesses.",
          goals: ["Identify opposition shape within 5 min", "Anticipate plays before they develop", "Exploit tactical weaknesses consistently"],
          milestones: [{ name: "Pattern recognition", metric: "Identifies opposition patterns quickly" }, { name: "Exploitation", metric: "Creates advantage from tactical reads" }],
          key_skills: ["Advanced reading", "Pattern recognition", "Opposition analysis", "Predictive thinking"],
          drills: ["Game Reading", "Opposition Analysis", "Pattern Training", "Tactical Video Breakdown"],
        },
        {
          name: "System Flexibility",
          weeks: 12,
          focus: "Play competently in multiple formations and tactical approaches.",
          goals: ["Perform in 3+ formations at high level", "Switch systems mid-game seamlessly", "Understand every position's tactical role"],
          milestones: [{ name: "System versatility", metric: "High performance in 3+ systems" }, { name: "Mid-game adjustment", metric: "Adapts within 2 min of tactical change" }],
          key_skills: ["System fluency", "In-game adaptation", "Tactical versatility", "Coachability"],
          drills: ["Multi-Formation Training", "In-Game System Switch", "Role Rotation", "Tactical Briefing"],
        },
        {
          name: "Leadership & Organization",
          weeks: 12,
          focus: "Organize teammates tactically. Communicate effectively. Lead by example.",
          goals: ["Organize defensive shape vocally", "Direct pressing triggers", "Lead team through tactical adjustments"],
          milestones: [{ name: "Communication", metric: "Constant tactical communication" }, { name: "Teammate rating", metric: "Peers rate leadership 8+/10" }],
          key_skills: ["Tactical communication", "Organization", "Leadership", "Influence"],
          drills: ["Leadership Play", "Captain Scenarios", "Tactical Huddle", "Communication Drill"],
        },
        {
          name: "Match Strategy Mastery",
          weeks: 16,
          focus: "Game management at the highest level. Set pieces. Situational mastery.",
          goals: ["Manage all game states effectively", "Execute set pieces with 40%+ conversion", "Control tempo and rhythm"],
          milestones: [{ name: "Game management", metric: "Positive results in varied game states" }, { name: "Set-piece efficiency", metric: "40%+ set-piece conversion" }],
          key_skills: ["Game management", "Set-piece mastery", "Tempo control", "Situational intelligence"],
          drills: ["Game Scenario Training", "Set-Piece Library", "Tempo Control Drill", "Situational Scrimmages"],
        },
      ],
    },
    mental: {
      vision: "Elite mindset. Perform under maximum pressure. Mental resilience at the highest level. Champion mentality.",
      phases: [
        {
          name: "Pressure Performance",
          weeks: 12,
          focus: "Execute when it matters most. Handle high-stakes situations.",
          goals: ["Maintain technique under maximal pressure", "Perform in clutch moments", "Stay composed in high-stakes scenarios"],
          milestones: [{ name: "Pressure rating", metric: "Coach-rated composure 8+/10" }, { name: "Clutch performance", metric: "Delivers in key moments" }],
          key_skills: ["Pressure composure", "Clutch performance", "Emotional control", "Focus"],
          drills: ["Pressure Simulation", "Clutch Moment Practice", "Penalty Shootout Psychology", "High-Stakes Scenarios"],
        },
        {
          name: "Elite Mindset",
          weeks: 12,
          focus: "Champion mentality. Process over outcome. Continuous improvement.",
          goals: ["Maintain process focus regardless of result", "Set and pursue elite-level goals", "Show relentless improvement mindset"],
          milestones: [{ name: "Mindset assessment", metric: "Psychometric champion profile" }, { name: "Goal attainment", metric: "Hits 80%+ of process goals" }],
          key_skills: ["Champion mindset", "Process focus", "Goal pursuit", "Continuous improvement"],
          drills: ["Mindset Training", "Process Goal Tracking", "Champion Journal", "Elite Athlete Study"],
        },
        {
          name: "Emotional Mastery",
          weeks: 12,
          focus: "Control emotions. Channel adrenaline. Stay calm under provocation.",
          goals: ["Maintain emotional control in heated moments", "Channel nervous energy positively", "Stay level after both wins and losses"],
          milestones: [{ name: "Emotional control", metric: "No cards for emotional reactions" }, { name: "Consistency", metric: "Stable emotional baseline" }],
          key_skills: ["Emotional regulation", "Adrenaline channeling", "Equanimity", "Self-awareness"],
          drills: ["Emotion Regulation Training", "Breath Work", "Meditation Practice", "Trigger Identification"],
        },
        {
          name: "Professional Mindset",
          weeks: 16,
          focus: "Total professional approach. Preparation, recovery, lifestyle, standards.",
          goals: ["Live a professional lifestyle consistently", "Set and maintain high standards", "Be a role model for younger players"],
          milestones: [{ name: "Professional rating", metric: "Coach-rated professionalism 9+/10" }, { name: "Standards consistency", metric: "Meets standards 95%+ of time" }],
          key_skills: ["Professionalism", "Standards", "Role modeling", "Lifestyle"],
          drills: ["Professional Standards Audit", "Lifestyle Planning", "Mentorship Practice", "Career Vision Board"],
        },
      ],
    },
    nutrition: {
      vision: "Performance nutrition mastery. Fuel for peak output. Body composition optimization. Tournament and travel nutrition.",
      phases: [
        {
          name: "Performance Fueling",
          weeks: 12,
          focus: "Optimize macro and micronutrient intake for peak performance.",
          goals: ["Hit macro targets consistently", "Optimize meal timing around training", "Maintain optimal body composition"],
          milestones: [{ name: "Macro compliance", metric: "80%+ compliance to targets" }, { name: "Body composition", metric: "In position-specific range" }],
          key_skills: ["Macro optimization", "Meal timing", "Body composition", "Performance fueling"],
          drills: ["Macro Tracking", "Timing Optimization", "Body Comp Monitoring", "Performance Plate Building"],
        },
        {
          name: "Competition Nutrition",
          weeks: 12,
          focus: "Game-day fueling strategy. Pre-match, halftime, post-match nutrition.",
          goals: ["Execute game-day nutrition plan", "Fuel properly at halftime", "Optimize 24h post-match recovery nutrition"],
          milestones: [{ name: "Game-day execution", metric: "Follows plan every match" }, { name: "Recovery compliance", metric: "Post-match nutrition on point" }],
          key_skills: ["Game-day fueling", "Halftime nutrition", "Recovery fueling", "Competition prep"],
          drills: ["Game-Day Meal Plan", "Halftime Fuel Strategy", "Recovery Window Nutrition", "Tournament Planning"],
        },
        {
          name: "Supplementation Strategy",
          weeks: 12,
          focus: "Evidence-based supplementation. What, when, and why. Safety and anti-doping.",
          goals: ["Understand supplement categories", "Use only safe, effective supplements", "Know anti-doping rules"],
          milestones: [{ name: "Supplement knowledge", metric: "Correctly identifies evidence-based supplements" }, { name: "Safety awareness", metric: "Knows banned substance categories" }],
          key_skills: ["Supplement knowledge", "Evidence evaluation", "Anti-doping awareness", "Safety"],
          drills: ["Supplement Education", "Anti-Doping Training", "Label Reading Advanced", "Evidence Review"],
        },
        {
          name: "Travel & Lifestyle Nutrition",
          weeks: 16,
          focus: "Maintain nutrition quality during travel, tournaments, and busy schedules.",
          goals: ["Maintain nutrition on the road", "Plan for tournaments and camps", "Make quality choices in all situations"],
          milestones: [{ name: "Travel compliance", metric: "Nutrition quality maintained during travel" }, { name: "Tournament fueling", metric: "Follows tournament nutrition plan" }],
          key_skills: ["Travel nutrition", "Tournament planning", "Flexibility", "Quality choices"],
          drills: ["Travel Meal Planning", "Tournament Nutrition Guide", "Restaurant Strategy", "Busy Schedule Planning"],
        },
      ],
    },
    recovery: {
      vision: "World-class recovery protocols. Maximize adaptation between sessions. Injury resilience. Career longevity.",
      phases: [
        {
          name: "Advanced Recovery Protocols",
          weeks: 12,
          focus: "Multi-modal recovery: sleep, nutrition, soft tissue, compression, contrast therapy.",
          goals: ["Implement multi-modal recovery", "Use recovery tools effectively", "Feel fully recovered between sessions"],
          milestones: [{ name: "Recovery protocol", metric: "Multi-modal recovery 5+ days/week" }, { name: "Recovery rating", metric: "Self-rated recovery 8+/10" }],
          key_skills: ["Multi-modal recovery", "Tool proficiency", "Self-assessment", "Protocol design"],
          drills: ["Recovery Protocol Design", "Tool Training", "Self-Assessment", "Contrast Therapy"],
        },
        {
          name: "Sleep Performance",
          weeks: 12,
          focus: "Optimize sleep quality and duration for athletic performance.",
          goals: ["Sleep 8+ hours consistently", "Improve sleep quality score", "Nap strategically when needed"],
          milestones: [{ name: "Sleep quality", metric: "Sleep quality score 85+/100" }, { name: "Sleep consistency", metric: "Consistent schedule 6+/7 days" }],
          key_skills: ["Sleep optimization", "Nap strategy", "Circadian rhythm", "Environment"],
          drills: ["Sleep Tracking", "Circadian Optimization", "Nap Protocol", "Environment Audit"],
        },
        {
          name: "Load Management",
          weeks: 12,
          focus: "Monitor and manage training load. Prevent overtraining. Optimize training stimulus.",
          goals: ["Track daily training load", "Identify overreaching early", "Adjust training based on readiness"],
          milestones: [{ name: "Load tracking", metric: "Daily load tracking compliance" }, { name: "Readiness response", metric: "Adjusts training based on data" }],
          key_skills: ["Load monitoring", "Readiness assessment", "Auto-regulation", "Prevention"],
          drills: ["Load Tracking", "Readiness Assessment", "Auto-Regulation Training", "Prevention Screening"],
        },
        {
          name: "Career Longevity",
          weeks: 16,
          focus: "Build habits for a long, healthy career. Balance, sustainability, and life after sport.",
          goals: ["Develop sustainable training habits", "Plan for career longevity", "Maintain love for the game"],
          milestones: [{ name: "Sustainability rating", metric: "Self-rated sustainability 9+/10" }, { name: "Love for game", metric: "Passion rating 9+/10" }],
          key_skills: ["Sustainability", "Career planning", "Balance", "Passion"],
          drills: ["Career Vision", "Sustainability Audit", "Balance Planning", "Joy in Sport"],
        },
      ],
    },
  },

  elite: {
    technical: {
      vision: "World-class technical execution. Innovation and creativity. Technical leadership. Define your unique playing style.",
      phases: [
        {
          name: "Technical Innovation",
          weeks: 12,
          focus: "Develop unique technical signature. Creative expression. Pushing technical boundaries.",
          goals: ["Create a signature move/style", "Innovate new solutions in matches", "Be technically unpredictable"],
          milestones: [{ name: "Signature development", metric: "Identifiable unique style" }, { name: "Innovation frequency", metric: "Novel solutions in matches" }],
          key_skills: ["Innovation", "Creativity", "Signature development", "Unpredictability"],
          drills: ["Creative Play (Elite)", "Signature Development", "Innovation Scenarios", "Style Refinement"],
        },
        {
          name: "Technical Perfection",
          weeks: 12,
          focus: "Eliminate technical weaknesses. Achieve near-perfect execution consistency.",
          goals: ["Execute all techniques at 95%+ accuracy", "No technical weaknesses identified", "Be the technical standard for your position"],
          milestones: [{ name: "Accuracy benchmark", metric: "95%+ across all techniques" }, { name: "Coach assessment", metric: "No identified weaknesses" }],
          key_skills: ["Perfection pursuit", "Weakness elimination", "Consistency", "Technical leadership"],
          drills: ["Precision Training", "Weakness Target Training", "Consistency Challenge", "Peer Coaching"],
        },
        {
          name: "Game Impact",
          weeks: 12,
          focus: "Maximize technical impact on match outcomes. Game-changing moments.",
          goals: ["Create match-defining moments weekly", "Be the technical difference-maker", "Lead team technically"],
          milestones: [{ name: "Impact metrics", metric: "Match-defining contributions" }, { name: "Team influence", metric: "Technical leader recognized by team" }],
          key_skills: ["Match impact", "Moment creation", "Technical leadership", "Clutch execution"],
          drills: ["Impact Training", "Moment Simulation", "Leadership Practice", "Performance Analysis"],
        },
        {
          name: "Technical Legacy",
          weeks: 16,
          focus: "Maintain elite technical level. Mentor younger players. Continuous refinement.",
          goals: ["Maintain elite technical standard", "Mentor 2+ developing players", "Continuously refine technique"],
          milestones: [{ name: "Standard maintenance", metric: "Elite benchmark maintained" }, { name: "Mentorship", metric: "Active mentor to developing players" }],
          key_skills: ["Maintenance", "Mentorship", "Refinement", "Legacy"],
          drills: ["Maintenance Program", "Mentorship Sessions", "Continuous Refinement", "Legacy Documentation"],
        },
      ],
    },
    physical: {
      vision: "Physical dominance. Peak human athletic performance. Injury-proof body. Maximum career longevity.",
      phases: [
        {
          name: "Peak Physical Development",
          weeks: 12,
          focus: "Achieve genetic physical potential. World-class athletic benchmarks.",
          goals: ["Hit elite-level physical benchmarks", "Show physical superiority on the pitch", "Be the physical standard"],
          milestones: [{ name: "Benchmark achievement", metric: "All physical benchmarks at elite level" }, { name: "Performance gap", metric: "No physical weakness vs competition" }],
          key_skills: ["Peak development", "Physical superiority", "Benchmark mastery", "Standard-setting"],
          drills: ["Elite Physical Program", "Benchmark Testing", "Superiority Training", "Physical Leadership"],
        },
        {
          name: "Injury Proofing",
          weeks: 12,
          focus: "Build an injury-resistant body. Pre-habilitation mastery. Load optimization.",
          goals: ["Complete season injury-free", "Pre-hab program at 95%+ compliance", "Optimize all physical loads"],
          milestones: [{ name: "Injury status", metric: "Zero preventable injuries" }, { name: "Pre-hab mastery", metric: "95%+ compliance" }],
          key_skills: ["Injury resilience", "Pre-hab mastery", "Load optimization", "Body intelligence"],
          drills: ["Injury-Proof Program", "Advanced Pre-hab", "Load Optimization", "Body Intelligence Training"],
        },
        {
          name: "Recovery Science",
          weeks: 12,
          focus: "Apply sports science to recovery. Optimize every recovery variable.",
          goals: ["Implement science-based recovery", "Use data to guide recovery", "Maximize adaptation between sessions"],
          milestones: [{ name: "Recovery optimization", metric: "Data-driven recovery protocol" }, { name: "Adaptation rate", metric: "Optimized training response" }],
          key_skills: ["Recovery science", "Data utilization", "Adaptation optimization", "Technology use"],
          drills: ["Science-Based Recovery", "Recovery Technology", "Data Analysis", "Adaptation Monitoring"],
        },
        {
          name: "Career Physical Longevity",
          weeks: 16,
          focus: "Maintain elite physical level for career duration. Age-appropriate adjustments.",
          goals: ["Adapt training to age/stage", "Maintain physical output over career", "Plan physical longevity strategy"],
          milestones: [{ name: "Longevity plan", metric: "Personalized longevity strategy active" }, { name: "Output maintenance", metric: "Elite output maintained" }],
          key_skills: ["Age adaptation", "Career planning", "Output maintenance", "Longevity strategy"],
          drills: ["Age-Appropriate Programming", "Career Physical Plan", "Maintenance Protocols", "Longevity Strategy"],
        },
      ],
    },
    tactical: {
      vision: "Tactical genius. Coach on the pitch. Anticipate and dictate. Master of all systems. Legacy of intelligence.",
      phases: [
        {
          name: "Tactical Mastery",
          weeks: 12,
          focus: "Complete tactical understanding. Read, predict, dictate play.",
          goals: ["Anticipate all tactical developments", "Dictate game tempo and flow", "Be the tactical reference point"],
          milestones: [{ name: "Tactical IQ", metric: "Coach-rated tactical intelligence elite" }, { name: "Game dictation", metric: "Controls game flow consistently" }],
          key_skills: ["Tactical genius", "Game dictation", "Prediction", "Reference role"],
          drills: ["Tactical Mastery Sessions", "Dictation Training", "Prediction Drills", "Coach-on-Pitch Practice"],
        },
        {
          name: "Strategic Leadership",
          weeks: 12,
          focus: "Lead the team's tactical execution. Coach on the field. Tactical mentor.",
          goals: ["Lead tactical meetings", "Coach teammates in-game", "Develop tactical leaders"],
          milestones: [{ name: "Leadership role", metric: "Recognized tactical leader" }, { name: "Mentor development", metric: "Develops 2+ tactical leaders" }],
          key_skills: ["Tactical leadership", "In-game coaching", "Mentoring", "Meeting facilitation"],
          drills: ["Tactical Leadership", "In-Game Coaching Practice", "Meeting Facilitation", "Mentor Sessions"],
        },
        {
          name: "Opposition Mastery",
          weeks: 12,
          focus: "Analyze and neutralize any opposition. Tactical adaptability.",
          goals: ["Analyze opposition within 10 min of video", "Create tactical solution for any system", "Exploit every opposition weakness"],
          milestones: [{ name: "Analysis speed", metric: "10-min opposition breakdown" }, { name: "Adaptability", metric: "Effective vs any system" }],
          key_skills: ["Opposition analysis", "Tactical adaptability", "Solution creation", "Exploitation"],
          drills: ["Opposition Analysis Advanced", "Adaptability Scenarios", "Solution Design", "Exploitation Training"],
        },
        {
          name: "Tactical Legacy",
          weeks: 16,
          focus: "Build a tactical philosophy. Mentor the next generation. Leave a tactical imprint.",
          goals: ["Develop personal tactical philosophy", "Mentor young players tactically", "Be remembered for tactical intelligence"],
          milestones: [{ name: "Philosophy development", metric: "Documented tactical philosophy" }, { name: "Mentorship impact", metric: "Mentees show tactical growth" }],
          key_skills: ["Philosophy building", "Legacy creation", "Mentorship", "Knowledge transfer"],
          drills: ["Philosophy Development", "Mentorship Program", "Knowledge Sharing", "Legacy Planning"],
        },
      ],
    },
    mental: {
      vision: "Unshakeable mentality. Elite performer under any pressure. Mental health mastery. Leadership through example.",
      phases: [
        {
          name: "Unshakeable Mindset",
          weeks: 12,
          focus: "Develop an impenetrable mental game. Handle any pressure, any situation.",
          goals: ["Stay composed in all situations", "Perform at peak under maximum pressure", "Be mentally unshakeable"],
          milestones: [{ name: "Composure rating", metric: "Coach-rated composure 10/10" }, { name: "Pressure test", metric: "Performance maintained regardless of pressure" }],
          key_skills: ["Mental unshakeability", "Pressure performance", "Emotional mastery", "Composure"],
          drills: ["Extreme Pressure Training", "Composure Practice", "Mental Toughness Circuit", "Crisis Simulation"],
        },
        {
          name: "Performance Psychology",
          weeks: 12,
          focus: "Advanced psychological skills. Flow state. Peak performance triggers.",
          goals: ["Access flow state on demand", "Use performance psychology tools", "Peak for key moments"],
          milestones: [{ name: "Flow state", metric: "Accesses flow state regularly" }, { name: "Psychology toolkit", metric: "Uses 5+ psychology tools effectively" }],
          key_skills: ["Flow state", "Psychology tools", "Peak performance", "Mental preparation"],
          drills: ["Flow State Training", "Psychology Toolkit", "Peak Performance Routine", "Pre-Performance Ritual"],
        },
        {
          name: "Mental Health & Balance",
          weeks: 12,
          focus: "Prioritize mental health. Work-life balance. Identity beyond sport.",
          goals: ["Maintain excellent mental health", "Achieve sustainable work-life balance", "Develop identity beyond soccer"],
          milestones: [{ name: "Mental health", metric: "Well-being score excellent" }, { name: "Life balance", metric: "Satisfaction in all life areas 8+/10" }],
          key_skills: ["Mental health", "Life balance", "Identity development", "Well-being"],
          drills: ["Mental Health Practice", "Balance Assessment", "Identity Exploration", "Well-Being Routine"],
        },
        {
          name: "Mental Leadership",
          weeks: 16,
          focus: "Lead through mental strength. Inspire teammates. Create a mentally strong culture.",
          goals: ["Be the mental anchor for the team", "Inspire teammates mentally", "Build a resilient team culture"],
          milestones: [{ name: "Leadership impact", metric: "Team mental strength improves" }, { name: "Culture building", metric: "Resilient culture evident" }],
          key_skills: ["Mental leadership", "Inspiration", "Culture building", "Team resilience"],
          drills: ["Mental Leadership Practice", "Team Building", "Culture Development", "Inspiration Training"],
        },
      ],
    },
    nutrition: {
      vision: "World-class nutrition discipline. Performance body composition. Micronutrient optimization. Dietary leadership.",
      phases: [
        {
          name: "Elite Nutrition Discipline",
          weeks: 12,
          focus: "Perfect nutrition execution. Every meal optimized for performance.",
          goals: ["Achieve optimal body composition", "Hit all macro/micro targets", "Execute perfect nutrition daily"],
          milestones: [{ name: "Body composition", metric: "Optimal for position" }, { name: "Nutrition compliance", metric: "95%+ target adherence" }],
          key_skills: ["Nutrition discipline", "Body composition", "Micronutrient optimization", "Execution"],
          drills: ["Elite Nutrition Plan", "Body Composition Tracking", "Micronutrient Optimization", "Execution Auditing"],
        },
        {
          name: "Performance Nutrition Science",
          weeks: 12,
          focus: "Apply latest nutrition science. Personalized fueling. Gut training.",
          goals: ["Implement personalized nutrition", "Optimize gut for performance", "Use cutting-edge nutrition strategies"],
          milestones: [{ name: "Personalization", metric: "Fully personalized nutrition plan" }, { name: "Science application", metric: "Uses 3+ evidenced strategies" }],
          key_skills: ["Nutrition science", "Personalization", "Gut optimization", "Innovation"],
          drills: ["Science Review", "Personalization Protocol", "Gut Training", "Innovation Application"],
        },
        {
          name: "Education & Leadership",
          weeks: 12,
          focus: "Become a nutrition resource. Educate teammates. Lead nutritionally.",
          goals: ["Educate teammates on nutrition", "Be a nutrition role model", "Create team nutrition resources"],
          milestones: [{ name: "Education impact", metric: "Teammates show nutrition improvement" }, { name: "Role model", metric: "Recognized nutrition leader" }],
          key_skills: ["Nutrition education", "Role modeling", "Leadership", "Resource creation"],
          drills: ["Education Sessions", "Role Model Practice", "Resource Development", "Team Nutrition Initiative"],
        },
        {
          name: "Lifetime Nutrition",
          weeks: 16,
          focus: "Build sustainable nutrition habits for life. Post-career health. Nutritional legacy.",
          goals: ["Develop lifetime nutrition plan", "Prepare for post-career health", "Be a lifelong healthy eater"],
          milestones: [{ name: "Lifetime plan", metric: "Sustainable nutrition plan active" }, { name: "Health forecast", metric: "Post-career health plan established" }],
          key_skills: ["Sustainability", "Life planning", "Health focus", "Habit permanence"],
          drills: ["Lifetime Nutrition Plan", "Post-Career Health Prep", "Habit Anchoring", "Health Legacy"],
        },
      ],
    },
    recovery: {
      vision: "Recovery mastery. Maximize every hour between sessions. Sleep, technology, science. Extend prime years.",
      phases: [
        {
          name: "Recovery Technology",
          weeks: 12,
          focus: "Leverage recovery technology. Data-driven recovery optimization.",
          goals: ["Use recovery technology daily", "Base recovery on objective data", "Optimize every recovery variable"],
          milestones: [{ name: "Technology use", metric: "Uses 3+ recovery technologies" }, { name: "Data integration", metric: "All recovery decisions data-backed" }],
          key_skills: ["Technology", "Data analysis", "Optimization", "Integration"],
          drills: ["Technology Protocol", "Data Analysis", "Variable Optimization", "Tech Integration"],
        },
        {
          name: "Sleep Mastery",
          weeks: 12,
          focus: "World-class sleep protocol. Optimize every sleep variable.",
          goals: ["Achieve sleep score 90+/100", "Optimize sleep environment fully", "Master sleep consistency"],
          milestones: [{ name: "Sleep score", metric: "90+/100 consistently" }, { name: "Environment", metric: "Fully optimized sleep environment" }],
          key_skills: ["Sleep mastery", "Environment", "Consistency", "Optimization"],
          drills: ["Sleep Optimization", "Environment Setup", "Consistency Protocol", "Tracking & Adjustment"],
        },
        {
          name: "Prime Extension",
          weeks: 12,
          focus: "Extend physical prime through recovery excellence.",
          goals: ["Maintain prime physical output", "Slow age-related decline", "Feel younger than biological age"],
          milestones: [{ name: "Prime maintenance", metric: "Output maintained vs 5-year benchmark" }, { name: "Biological advantage", metric: "Recovery age below biological age" }],
          key_skills: ["Prime extension", "Age management", "Decline prevention", "Youthful output"],
          drills: ["Prime Extension Program", "Age Management", "Decline Prevention", "Output Tracking"],
        },
        {
          name: "Recovery Leadership",
          weeks: 16,
          focus: "Lead recovery culture. Educate and inspire. Set the recovery standard.",
          goals: ["Lead by example in recovery", "Educate team on recovery", "Build a recovery-focused culture"],
          milestones: [{ name: "Example setting", metric: "Recognized recovery leader" }, { name: "Culture impact", metric: "Team recovery practices improve" }],
          key_skills: ["Recovery leadership", "Education", "Culture building", "Standard setting"],
          drills: ["Leadership Practice", "Team Education", "Culture Initiative", "Standard Documentation"],
        },
      ],
    },
  },
};

// ── Summary helpers ──
export function getPlayerIdp(playerAge, pillar) {
  const group = getAgeGroup(playerAge);
  return IDP_LIBRARY[group.key]?.[pillar] || null;
}

export function getAllPillarProgress(playerAge, categoryXp = {}) {
  const group = getAgeGroup(playerAge);
  const pillars = Object.keys(PILLARS);
  return pillars.map((pillar) => {
    const idp = IDP_LIBRARY[group.key]?.[pillar];
    const totalPhases = idp?.phases?.length || 4;
    const totalWeeks = idp ? idp.phases.reduce((sum, p) => sum + p.weeks, 0) : 52;
    const pillarXp = categoryXp[pillar] || 0;
    // Estimate phase completion: each phase has ~25% of total weeks
    const weeksPerPhase = Math.round(totalWeeks / totalPhases);
    const completedPhases = Math.min(Math.floor(pillarXp / (weeksPerPhase * 15)), totalPhases);
    const currentPhaseProgress = Math.min(((pillarXp % (weeksPerPhase * 15)) / (weeksPerPhase * 15)) * 100, 100);
    return {
      pillar,
      label: PILLARS[pillar].label,
      icon: PILLARS[pillar].icon,
      color: PILLARS[pillar].color,
      vision: idp?.vision || "",
      totalPhases,
      completedPhases: completedPhases > totalPhases ? totalPhases : completedPhases,
      currentPhase: idp?.phases?.[completedPhases] || null,
      currentPhaseProgress: completedPhases >= totalPhases ? 100 : currentPhaseProgress,
      phases: idp?.phases || [],
      isComplete: completedPhases >= totalPhases,
    };
  });
}